In [1]:
import numpy as np


In [3]:
my1D_arr = np.array([4,6,7,9,2,5])
print(my1D_arr)

[4 6 7 9 2 5]


In [4]:
x1 = np.random.randint(10, size=6)
print(x1)

[3 3 9 2 9 1]


In [5]:
x2 = np.random.randint(10, size=(3, 5))
print(x2)

[[3 4 2 2 1]
 [2 7 9 8 2]
 [4 8 7 6 4]]


In [14]:
x3 = np.random.randint(10, size=(3, 5, 2))
print(x3)

[[[6 5]
  [5 5]
  [7 5]
  [8 9]
  [0 1]]

 [[2 5]
  [9 0]
  [8 4]
  [6 1]
  [8 2]]

 [[6 2]
  [0 3]
  [2 1]
  [8 1]
  [1 5]]]


In [9]:
my2D_arr = np.array([[4,6,7,9,2,5],[4,6,6,2,1,9], [4,6,7,9,2,5], [4,6,7,9,2,5]])
print(my2D_arr)

[[4 6 7 9 2 5]
 [4 6 6 2 1 9]
 [4 6 7 9 2 5]
 [4 6 7 9 2 5]]


In [10]:
print(my2D_arr.shape)

(4, 6)


In [11]:
print(my2D_arr.data)

In [12]:
print(my2D_arr.dtype)

int32


In [20]:
one_array = np.zeros((2,8), dtype=np.int16)
print(one_array)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [19]:
print(one_array.dtype)

int16


In [21]:
array = np.linspace(4, 9, 10)
print(array)

[4.         4.55555556 5.11111111 5.66666667 6.22222222 6.77777778
 7.33333333 7.88888889 8.44444444 9.        ]


In [22]:
y1 = np.random.randint(10, size=18)
print(y1)

[8 4 9 5 0 0 1 6 4 1 1 9 6 6 5 8 8 0]


In [23]:
print(y1[1:7])

[4 9 5 0 0 1]


In [29]:
print(y1[::2])

[8 9 0 1 4 1 6 5 8]


In [31]:
print(y1.sum())

81


In [32]:
xx = np.random.randint(18, size=(5, 3))
print(xx)


[[12  0  8]
 [ 5  7 10]
 [ 6  4  1]
 [17 12  1]
 [15  6  5]]


In [34]:
print(xx[1,2])

10


In [36]:
print(xx[1:3:])

[[ 5  7 10]
 [ 6  4  1]]


In [55]:
print(xx[[1,2],:])

[[ 5  7 10]
 [ 6  4  1]]


In [60]:
x = np.array([[2, 4, 7], [5, 8, 2]])
y = np.array([[1, 7, 3], [-1, 5, 9]])
print(x.shape, y.shape)
add = np.add(x, y)
sub = np.subtract(x, y)
mul = np.multiply(x, y)
div = np.divide(x, y)
print(add, sub, mul, div)
print(x+y)

(2, 3) (2, 3)
[[ 3 11 10]
 [ 4 13 11]] [[ 1 -3  4]
 [ 6  3 -7]] [[ 2 28 21]
 [-5 40 18]] [[ 2.          0.57142857  2.33333333]
 [-5.          1.6         0.22222222]]
[[ 3 11 10]
 [ 4 13 11]]


In [63]:
class calculator:
    def add(self, a, b):
        return a+b

    def multiply(self, a, b):
        return a*b

    def divide(self, a, b):
        if b!=0:
            return a/b
        else:
            return "Error: Divide be zero condition!"

if __name__== "__main__":
    calc = calculator()
    div = calc.divide(3, 6)
    print("The divided result is:", div)
    print("The multiplication result is:", calc.multiply(8, 5))
        

The divided result is: 0.5
The multiplication result is: 40


In [18]:
import pandas as pd
data = pd.read_csv("C:/Users/USER/Desktop/BETKOT Municipality Program/YASH SLIDES/Class4_CSV Operation/CSV_File_Basic/employee.csv")
print(data.head())
print(data.tail())
print(data.columns)
print(data.shape)
print(data.info())
print(data.describe())
print(data.filter(["name", "age"]))

            name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
            name   age   income gender  department grade  performance_score
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3                649
6   James Authur  54.0      NaN      F  Operations    G3                 53
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709
Index(['name', 'age', 'income', 'gender', 'department', 'grade',
       'performance_sco

In [19]:
print(data[2:6])

            name   age   income gender  department grade  performance_score
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3                649


In [29]:
print(data[data.department.isin(['Sales', 'Finance'])])

            name   age   income gender department grade  performance_score
1        S Kumar   NaN  16000.0      F    Finance    G0                520
2    Jack Morgan  32.0  35000.0      M    Finance    G2                674
3      Ying Chin  45.0  65000.0      F      Sales    G3                556
5  Satyam Sharma   NaN  62000.0    NaN      Sales    G3                649
7     Josh Wills  54.0  52000.0      F    Finance    G3                901
8       Leo Duck  23.0  98000.0      M      Sales    G4                709


In [30]:
print(data[data.performance_score>=700])

            name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709


In [31]:
print(data[(data.performance_score>=500)& (data.performance_score<800)])

            name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3                649
8       Leo Duck  23.0  98000.0      M       Sales    G4                709
